name: Question or other
description: Ask a question or raise anything that does not fit the other forms
labels: ["type: question", "status: needs triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question or comment
    validations:
      required: true
