"""Build The ELSA Way toolbox from the YAML tool entries.

Reads toolbox/tools/*.yml, validates each entry against
toolbox/schema.json, checks every passage reference against the book,
and writes the generated Markdown that the book includes:

    website/toolbox/tools/tool-<id>.md            one page per tool
    website/toolbox/_generated/passages/<id>.md   "Tools for this step" boxes
    website/toolbox/_generated/overview.md        overview tables
    website/toolbox/_generated/audiences/<a>.md   tool lists for the pathways

A passage is defined in the chapter itself, by including its box under the
right heading:

    :::{include} ../toolbox/_generated/passages/<passage-id>.md
    :::

Usage:
    python scripts/build_toolbox.py           validate and generate
    python scripts/build_toolbox.py --check   validate only
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import jsonschema
import yaml

BOOK = Path(__file__).resolve().parent.parent
WEBSITE = BOOK / "website"
TOOLS_DIR = BOOK / "toolbox" / "tools"
SCHEMA = BOOK / "toolbox" / "schema.json"
OUT_TOOLS = WEBSITE / "toolbox" / "tools"
OUT_GEN = WEBSITE / "toolbox" / "_generated"
REPO_URL = "https://github.com/the-elsa-way/the-elsa-way"

INCLUDE_RE = re.compile(r"^:::\{include\}\s+\S*toolbox/_generated/passages/([a-z0-9-]+)\.md\s*$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")

PHASES = {
    "design": "Design",
    "development": "Development",
    "evaluation": "Evaluation",
    "deployment": "Deployment",
}
PRINCIPLES = {
    "fairness": "Fairness",
    "universality": "Universality",
    "traceability": "Traceability",
    "usability": "Usability",
    "robustness": "Robustness",
    "explainability": "Explainability",
    "general": "General recommendations",
}
AUDIENCES = {
    "ai-developers": "AI developers",
    "healthcare-professionals": "Healthcare professionals",
    "patients-communities": "Patients and communities",
    "researchers": "Researchers",
    "policy-managers": "Policy makers and managers",
}
TYPES = {
    "technical-library": "Software library",
    "assessment": "Assessment",
    "reporting-guideline": "Reporting guideline",
    "participatory-method": "Participatory method",
    "serious-game": "Serious game",
    "canvas": "Canvas",
    "framework": "Framework",
    "questionnaire": "Questionnaire",
}
FACILITATOR = {
    "required": "Facilitator required",
    "recommended": "Facilitator recommended",
    "not-needed": "No facilitator needed",
}
COST = {"free": "Free", "paid": "Paid", "freemium": "Free and paid tiers", "on-request": "Ask the developers"}
LANGUAGES = {
    "de": "German", "el": "Greek", "en": "English", "es": "Spanish", "fi": "Finnish", "fr": "French",
    "it": "Italian", "ja": "Japanese", "nl": "Dutch", "pt": "Portuguese",
}
MATURITY = {"established": "Established", "emerging": "Emerging"}

GENERATED_NOTICE = "% Generated by scripts/build_toolbox.py. Do not edit; edit toolbox/tools/*.yml instead.\n"


@dataclass
class Passage:
    id: str
    file: Path
    line: int
    page_title: str
    section: str

    @property
    def label(self) -> str:
        return f"tools-{self.id}"

    @property
    def title(self) -> str:
        return f"{self.page_title} › {self.section}"


def load_tools(errors: list[str]) -> dict[str, dict]:
    schema = json.loads(SCHEMA.read_text())
    validator = jsonschema.Draft202012Validator(schema)
    tools = {}
    for path in sorted(TOOLS_DIR.glob("*.yml")):
        rel = path.relative_to(BOOK)
        try:
            tool = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            errors.append(f"{rel}: invalid YAML: {exc}")
            continue
        if not isinstance(tool, dict):
            errors.append(f"{rel}: expected a mapping of fields")
            continue
        # YAML reads an unquoted 2026-01-31 as a date; the schema expects a string.
        if isinstance(tool.get("last_reviewed"), datetime.date):
            tool["last_reviewed"] = tool["last_reviewed"].isoformat()
        problems = sorted(validator.iter_errors(tool), key=lambda e: list(e.path))
        for err in problems:
            where = "/".join(str(p) for p in err.path) or "(top level)"
            errors.append(f"{rel}: {where}: {err.message}")
        if problems:
            continue
        if tool["id"] != path.stem:
            errors.append(f"{rel}: id '{tool['id']}' must match the file name '{path.stem}'")
            continue
        tools[tool["id"]] = tool
    for tool in tools.values():
        for other in tool.get("see_also", []):
            if other not in tools:
                errors.append(f"toolbox/tools/{tool['id']}.yml: see_also: unknown tool '{other}'")
    return tools


def find_passages(errors: list[str]) -> dict[str, Passage]:
    passages: dict[str, Passage] = {}
    for path in sorted(WEBSITE.rglob("*.md")):
        rel = path.relative_to(WEBSITE)
        if rel.parts[0] in ("_build",) or rel.parts[:2] in (("toolbox", "_generated"), ("toolbox", "tools")):
            continue
        page_title, section, fence = "", "", None
        for lineno, line in enumerate(path.read_text().splitlines(), start=1):
            # Skip fenced code blocks, so documentation examples are not taken as passages.
            if marker := FENCE_RE.match(line):
                if fence is None:
                    fence = marker.group(1)
                elif marker.group(1).startswith(fence):
                    fence = None
                continue
            if fence:
                continue
            if heading := HEADING_RE.match(line):
                level, text = len(heading.group(1)), heading.group(2)
                if level == 1 and not page_title:
                    page_title = text
                section = text
                continue
            if match := INCLUDE_RE.match(line):
                pid = match.group(1)
                if pid in passages:
                    first = passages[pid]
                    errors.append(
                        f"website/{rel}:{lineno}: passage '{pid}' is already included in "
                        f"website/{first.file.relative_to(WEBSITE)}:{first.line}"
                    )
                    continue
                passages[pid] = Passage(pid, path, lineno, page_title or rel.stem, section or page_title)
    return passages


def check_links(tools: dict[str, dict], passages: dict[str, Passage], errors: list[str]) -> None:
    used = set()
    for tool in tools.values():
        seen = set()
        for ref in tool["passages"]:
            if ref["id"] in seen:
                errors.append(f"toolbox/tools/{tool['id']}.yml: passage '{ref['id']}' is listed twice")
            seen.add(ref["id"])
            if ref["id"] not in passages:
                errors.append(
                    f"toolbox/tools/{tool['id']}.yml: passage '{ref['id']}' does not exist in the book. "
                    f"Add this line under the right heading in a chapter:\n"
                    f"    :::{{include}} <relative path>/toolbox/_generated/passages/{ref['id']}.md\n    :::"
                )
            used.add(ref["id"])
    for pid, passage in passages.items():
        if pid not in used:
            errors.append(
                f"website/{passage.file.relative_to(WEBSITE)}:{passage.line}: no tool points to passage '{pid}'. "
                f"Add it to a tool's passages, or remove the include."
            )


# --------------------------------------------------------------------------- rendering


def tool_link(tool: dict) -> str:
    return f"[{tool['name']}](#tool-{tool['id']})"


def one_line(text: str) -> str:
    return " ".join(text.split())


def table_cell(text: str) -> str:
    return one_line(text).replace("|", "\\|")


def render_passage(passage: Passage, entries: list[tuple[dict, str]]) -> str:
    lines = [
        GENERATED_NOTICE,
        f"({passage.label})=",
        ":::{admonition} Tools for this step",
        ":class: seealso",
    ]
    for tool, why in sorted(entries, key=lambda e: e[0]["name"].lower()):
        practical = tool["practical"]
        facts = [TYPES[tool["type"]], FACILITATOR[practical["facilitator"]].lower(), COST[practical["cost"]].lower()]
        lines.append(f"- **{tool_link(tool)}**: {one_line(why)} _({' · '.join(facts)})_")
    lines += ["", "See the [Toolbox](#toolbox) for more tools.", ":::", ""]
    return "\n".join(lines)


def render_tool(tool: dict, passages: dict[str, Passage], tools: dict[str, dict]) -> str:
    practical = tool["practical"]
    license_ = tool["license"]
    out = [GENERATED_NOTICE, f"(tool-{tool['id']})=", f"# {tool['name']}", "", f"_{one_line(tool['summary'])}_", ""]

    license_text = f"[{license_['name']}]({license_['url']})" if license_.get("url") else license_["name"]
    facts = [
        ("Full name", tool.get("full_name")),
        ("Website", f"<{tool['url']}>"),
        ("Source code", f"<{tool['source_code']}>" if tool.get("source_code") else None),
        ("Developed by", ", ".join(tool["developers"]) + (f" ({tool['year']})" if tool.get("year") else "")),
        ("Type", f"{TYPES[tool['type']]}: {tool['format']}"),
        ("Lifecycle phase", ", ".join(f"[{PHASES[p]}](#{p})" for p in tool["lifecycle"])),
        ("FUTURE-AI", ", ".join(PRINCIPLES[p] for p in tool["future_ai"])),
        ("For", ", ".join(AUDIENCES[a] for a in tool["audiences"])),
        ("Time needed", practical.get("duration")),
        ("Group size", practical.get("group_size")),
        ("Facilitation", FACILITATOR[practical["facilitator"]]),
        ("Skills needed", practical.get("skills")),
        ("Cost", COST[practical["cost"]]),
        ("Languages", ", ".join(LANGUAGES.get(code, code) for code in practical["languages"])),
        ("Maturity", MATURITY[tool["maturity"]]),
        ("Licence", license_text),
    ]
    out += ["| | |", "|---|---|"]
    out += [f"| **{key}** | {table_cell(value)} |" for key, value in facts if value]
    out += ["", "## What it is", "", tool["description"].strip(), ""]
    if tool.get("healthcare"):
        out += ["## In healthcare", "", tool["healthcare"].strip(), ""]

    out += ["## Where to use it in The ELSA Way", ""]
    for ref in tool["passages"]:
        passage = passages[ref["id"]]
        out.append(f"- [{passage.title}](#{passage.label}): {one_line(ref['why'])}")
    out.append("")

    if tool.get("references"):
        out += ["## References", ""]
        for ref in tool["references"]:
            link = f" <https://doi.org/{ref['doi']}>" if ref.get("doi") else (f" <{ref['url']}>" if ref.get("url") else "")
            out.append(f"- {one_line(ref['citation'])}{link}")
        out.append("")

    if tool.get("see_also"):
        out += ["## Related tools", ""]
        out += [f"- {tool_link(tools[other])}: {one_line(tools[other]['summary'])}" for other in tool["see_also"]]
        out.append("")

    if tool.get("also_listed_in"):
        listed = ", ".join(f"[{item['name']}]({item['url']})" for item in tool["also_listed_in"])
        out += [f"Also listed in: {listed}.", ""]

    reuse = (
        "The licence allows The ELSA Way to reuse the tool's materials, with attribution."
        if license_["rehost"]
        else "The ELSA Way describes and links to this tool but does not copy its materials. Get them from the developer's website."
    )
    out += [
        ":::{note} About this entry",
        f"{reuse} Facts last checked on {tool['last_reviewed']}. "
        f"Spotted an error? [Edit this entry on GitHub]({REPO_URL}/edit/main/toolbox/tools/{tool['id']}.yml).",
        ":::",
        "",
    ]
    return "\n".join(out)


def render_overview(tools: dict[str, dict]) -> str:
    ordered = sorted(tools.values(), key=lambda t: t["name"].lower())
    out = [GENERATED_NOTICE, "## Tools by lifecycle phase", ""]
    for phase, phase_name in PHASES.items():
        in_phase = [t for t in ordered if phase in t["lifecycle"]]
        if not in_phase:
            continue
        out += [f"### {phase_name}", "", "| Tool | What it helps you do | Type | Facilitation | Cost |", "|---|---|---|---|---|"]
        for tool in in_phase:
            practical = tool["practical"]
            out.append(
                f"| {tool_link(tool)} | {table_cell(tool['summary'])} | {TYPES[tool['type']]} "
                f"| {FACILITATOR[practical['facilitator']]} | {COST[practical['cost']]} |"
            )
        out.append("")

    out += [
        "## Tools by FUTURE-AI principle",
        "",
        "Each cell lists the tools that support a FUTURE-AI principle in a lifecycle phase.",
        "",
        "| Principle | " + " | ".join(PHASES.values()) + " |",
        "|---|" + "---|" * len(PHASES),
    ]
    for principle, principle_name in PRINCIPLES.items():
        cells = []
        for phase in PHASES:
            matching = [tool_link(t) for t in ordered if principle in t["future_ai"] and phase in t["lifecycle"]]
            cells.append(", ".join(matching) or "–")
        out.append(f"| **{principle_name}** | " + " | ".join(cells) + " |")
    out.append("")

    out += ["## Tools by type", ""]
    for type_, type_name in TYPES.items():
        of_type = [tool_link(t) for t in ordered if t["type"] == type_]
        if of_type:
            out.append(f"- **{type_name}**: {', '.join(of_type)}")
    out.append("")
    return "\n".join(out)


def render_audience(audience: str, tools: dict[str, dict]) -> str:
    ordered = sorted((t for t in tools.values() if audience in t["audiences"]), key=lambda t: t["name"].lower())
    out = [GENERATED_NOTICE, ":::{admonition} Tools for you", ":class: seealso"]
    if ordered:
        out += [f"- **{tool_link(t)}**: {one_line(t['summary'])}" for t in ordered]
    else:
        out.append("No tools are listed for this audience yet.")
    out += ["", "See the [Toolbox](#toolbox) for all tools.", ":::", ""]
    return "\n".join(out)


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def generate(tools: dict[str, dict], passages: dict[str, Passage]) -> None:
    for directory in (OUT_TOOLS, OUT_GEN):
        if directory.exists():
            shutil.rmtree(directory)

    for tool in tools.values():
        write(OUT_TOOLS / f"tool-{tool['id']}.md", render_tool(tool, passages, tools))

    by_passage: dict[str, list[tuple[dict, str]]] = {pid: [] for pid in passages}
    for tool in tools.values():
        for ref in tool["passages"]:
            by_passage[ref["id"]].append((tool, ref["why"]))
    for pid, entries in by_passage.items():
        write(OUT_GEN / "passages" / f"{pid}.md", render_passage(passages[pid], entries))

    write(OUT_GEN / "overview.md", render_overview(tools))
    for audience in AUDIENCES:
        write(OUT_GEN / "audiences" / f"{audience}.md", render_audience(audience, tools))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="validate only; do not write files")
    args = parser.parse_args()

    errors: list[str] = []
    tools = load_tools(errors)
    passages = find_passages(errors)
    check_links(tools, passages, errors)
    if errors:
        print(f"Toolbox: {len(errors)} problem(s) found:\n", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    if not args.check:
        generate(tools, passages)
    print(f"Toolbox: {len(tools)} tools, {len(passages)} passages OK" + ("" if args.check else ", pages generated"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
